name: Lab02 Reuse and Artifacts
run-name: Lab02 - ${{ github.actor }} is calling Composite Actions 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-dotnet-app
        id: build
        with:
          folder-path: apps/uptodate-app
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.output-directory-path }}

  greeter-job:
    uses: ./.github/workflows/greeter.yml
