name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:

env:
  MY_VARIABLE: "Hello, GitHub Actions!"

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing MY_VARIABLE
        run: echo "MY_VARIABLE is $MY_VARIABLE!"
      - name: Printing DEMO_SECRET
        run: echo "DEMO_SECRET is ${{secrets.DEMO_SECRET}}!"
